name: Compile Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm-version: [ "1.10", "1.11" ]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Ohh it's a steup, it's a setup...
      run: |
        SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
        echo ::set-env name=SOURCEMOD_PATH::$SOURCEMOD_PATH
        echo ::set-env name=SCRIPTS_PATH::$SOURCEMOD_PATH/scripting
        echo ::set-env name=INCLUDE_PATH::$SOURCEMOD_PATH/scripting/include
        
    - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
      uses: rumblefrog/setup-sp@master
      with:
        version: ${{ matrix.SM_VERSION }}
      
    - name: Go fetch! Good Doggo!
      run: |
        wget https://github.com/Impact123/AutoExecConfig/raw/development/autoexecconfig.inc -P $INCLUDE_PATH
        
    - name: Compile!
      run: |
        echo -e "\nCompiling SurfTimer.sp..."
        spcomp -w234 -O2 -v2 -i $INCLUDE_PATH
        
